### ISSUE TITLE
Not able to install this software properly in ARC/HTC cluster

### ISSUE THREAD

**Issue by shrutiOx** [jackievaleri/BioSeqAutoML#4]
Hi,

Following all the instructions (using git clone route) I tried to install this package in HTC cluster. However although it did not throw any error during installation, but  in the BioAutoMATED folder  there is no code/modules when  I launched the same using Jupyter notebook. Using docker Icould successfully install in Win 11, however the tool could not process sequences with length > 300 in the same machine (intel i5, NVIDIA-GeForce GTX-1650 Ti)  so Itried to install it in ARC cluster which has more memory capability , in order to process these sequences.

Can you please advice on this. Thanks!

**Comment by jackievaleri** [comment]
Hi Shruti, thanks for reaching out and I am sorry that you are having issues. First, I am happy to hear that you can successfully install BioAutoMATED in Windows 11 via Docker. You should also be able to install the code on a cluster as well. After installing via Docker, the localhost:8888 port should look something like this: <img width="814" alt="Docker_route" src="https://github.com/jackievaleri/BioAutoMATED/assets/33818756/b8ac4096-6566-4132-b293-706b814b3a1d">
The code can be found under BioAutoMATED/main_classes/. 

After installing via git clone, the BioAutoMATED folder should have many similar elements, including the main_classes/ folder where the main python scripts can be found. The folder should look like this: <img width="473" alt="GitHub_route" src="https://github.com/jackievaleri/BioAutoMATED/assets/33818756/38ad8d33-f4e6-4cbd-ba4a-485ec10481da">
Can you provide more details about what the installed BioAutoMATED folder contains via the git clone route on the ARC cluster? It might be that the download was incomplete and perhaps you can try to clone the folder again and verify if this solves the issue.

I will also add a quick note that a known limitation of BioAutoMATED is longer range sequences; we only tested sequences up to several hundred base pairs. The computational complexity of datasets with longer sequences is high and the model architectures we chose to explore with BioAutoMATED are not necessarily suited for longer sequences. Your experiment should still work, but please keep these limitations in mind.

**Comment by shrutiOx** [comment]
Hello,

Thank you very much for getting back to me and I apologize for late response. I could successfully install this software in Cluster. This is a very good package overall. Thanks for your contribution.

**Comment by jackievaleri** [comment]
Wonderful news! Let me know if any other questions or issues pop up and thanks for using BioAutoMATED!
