### ISSUE TITLE
Issues creating an image from dockerfile

### ISSUE THREAD

**Issue by lucaskbobadilla** [jackievaleri/BioSeqAutoML#5]
Hello,

I am trying to build an image from the dockerfile into a kubernates to spin a pod with this image. I am getting an error at the following step:

```
> [20/20] COPY BioAutoMATED/ ./BioAutoMATED/:
------
failed to compute cache key: failed to calculate checksum of ref 9960a4ca-465e-4871-8fe9-8f473e306ac1::3k0n4n1u476kkmvn29zqg9ero: "/BioAutoMATED": not found
```

Any ideas?

**Comment by lucaskbobadilla** [comment]
Fixed. In case you want to build the image in a internal hub instead of dockerhub, just change: `COPY bioautoMATED/ ./bioautoMATED/` for `COPY . .` in the dockerfile.

Cheers and thanks for the great tool!

**Comment by jackievaleri** [comment]
Thanks for posting this solution, Lucas! Happy you were able to figure it out :)
